config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recipes#recommended"

  resources :recipes, only: %i[index show]
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

	validates_uniqueness_of :name, message: "already exists"

	has_many :recipe_ingredients
	has_many :recipes, through: :recipe_ingredients

	UNITS = %w[
		gram
		kilogram
		liter
		milliliter
		teaspoon
		tablespoon
		cup
		pound
		fluid_ounce
	].freeze

	scope :has_quantity, -> { where.not(quantity: [nil, 0]) }

end

app/models/recipe.rb
class Recipe < ApplicationRecord

	has_many :recipe_ingredients, dependent: :destroy
	has_many :ingredients, through: :recipe_ingredients, dependent: :destroy

	scope :can_be_made_with_ingredients, ->(ingredient_ids) {
		joins(:recipe_ingredients)
			.where(recipe_ingredients: { ingredient_id: ingredient_ids })
			.where.not(recipe_ingredients: { ingredient_id: nil })
			.group('recipes.id')
			.having('COUNT(recipe_ingredients.ingredient_id) = (SELECT COUNT(*) FROM recipe_ingredients WHERE recipe_ingredients.recipe_id = recipes.id)')
	}

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord

	belongs_to :ingredient, optional: true
	belongs_to :recipe

	scope :contains_ingredient, ->(ingredient) {
		where("ingredient_description ~* '\\m#{ingredient}\\M'")
	}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	def index
		@ingredients = Ingredient.all
	end

	def new
		@ingredient = Ingredient.new
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)
		@ingredient.save
		map_with_recipes

		redirect_to ingredients_path
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
	end

	def update
		@ingredient = Ingredient.find(params[:id])
		@ingredient.update(ingredient_params)
		map_with_recipes
		redirect_to ingredients_path
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		@ingredient.destroy
	end

	private

	def ingredient_params
		params.require(:ingredient).permit(:name, :quantity, :unit)
	end

	def map_with_recipes
		recipe_ingredients = RecipeIngredient.contains_ingredient(@ingredient.name)
		recipe_ingredients.update_all(ingredient_id: @ingredient.id)
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show ]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 28)
  end

  def show
  end

  def recommended
    @ingredients = Ingredient.has_quantity
    @recipes = Recipe.can_be_made_with_ingredients(@ingredients).paginate(page: params[:page], per_page: 30)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def decode_image_url(url)
		CGI.unescape(url)
	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.haml
= form_with(model: ingredient) do |form|
  - if ingredient.errors.any?
    %div{ style: "color: red" }
      %h2= "#{pluralize(ingredient.errors.count, "error")} prohibited this ingredient from being saved:"

      %ul
        - ingredient.errors.each do |error|
          %li= error.full_message

  %div
    = form.label :name, style: "display: block"
    = form.text_field :name

  %div
    = form.label :quantity, style: "display: block"
    = form.number_field :quantity

    = form.select :unit, Ingredient::UNITS, prompt: 'Select a unit'

  %div
    = form.submit

app/views/ingredients/_ingredient.html.haml
%a{ href: edit_ingredient_path(ingredient) }
  .ingredient{ id: dom_id(ingredient) }
    %h3= ingredient.name

    %div
      %small
        = 'Quantity'
        = ':'
      = "#{ingredient.quantity}"

app/views/ingredients/edit.html.haml
%h1 Update #{@ingredient.name}

= render 'form', ingredient: @ingredient

%div
  = link_to "Back to ingredients", :back

app/views/ingredients/index.html.haml
%h1= 'Your Ingredients'

.text-end
  = link_to "Add your ingredients", new_ingredient_path, class: 'btn btn-primary mb-3'

#ingredients
  - @ingredients.each do |ingredient|
    = render ingredient

app/views/ingredients/new.html.haml
%h1= 'Your Ingredients'

= render 'form', ingredient: @ingredient

%div
  = link_to "Back to ingredients", :back

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dinner Time!
    %meta{ name: "viewport", content: "width=device-width,initial-scale=1" }
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body
    .container-fluid
      %nav.navbar.navbar-expand-lg.bg-light
        %div.container
          %a.navbar-brand{ href: '/' }
            %h3 Dinner Time!
          %div.collapse.navbar-collapse#navbarTogglerDemo02
            %ul.navbar-nav.me-auto.mb-2.mb-lg-0
              %li.nav-item
                %a.nav-link{ href: recipes_path }
                  Explore Recipes
              %li.nav-item
                %a.nav-link{ href: ingredients_path }
                  Ingredients
      .container
        = yield

app/views/recipes/_recipe.html.haml
.recipe{ id: dom_id(recipe) }
  %img.recipe-image{ src: "#{decode_image_url(recipe.image)}?w=300" }

  %h3= recipe.title

  %div
    %small
      %i.fa-regular.fa-clock
      = 'Cooking:'
    = "#{recipe.cooking_time} minutes"

  %div
    %small
      %i.fa-regular.fa-clock
      = 'Preparation:'
    = "#{recipe.preparation_time} minutes"

app/views/recipes/index.html.haml
%h1= 'All Recipes'

.text-end
  = link_to "Add your ingredients", ingredients_path, class: 'btn btn-primary mb-3'

#recipes.d-flex.flex-wrap
  - @recipes.each do |recipe|
    %a{ href: recipe_path(recipe) }
      = render recipe

= will_paginate @recipes, inner_window: 3, outer_window: 1

app/views/recipes/recommended.html.haml
%h1= 'Dinner Time!'

%div
  %h4= 'Based on your ingredients these recipes are perfect for you!'

  .text-end
    = link_to "Add your ingredients", ingredients_path, class: 'btn btn-primary mb-3'

#recipes
  - @recipes.each do |recipe|
    %a{ href: recipe_path(recipe) }
      = render recipe

= will_paginate @recipes, inner_window: 1, outer_window: 1

app/views/recipes/show.html.haml
%img.recipe-main-image{ src: "#{decode_image_url(@recipe.image)}?w=600" }

%h1.text-start= @recipe.title

%ul
  - @recipe.recipe_ingredients.each do |ingredient|
    %li= ingredient.ingredient_description

%div
  = link_to "Back to recipes", :back